name: themes
description: Package de temas do Manga Easy.
version: 1.1.0
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  custom_lint: 0.4.0
  manga_easy_lint_rules:
    git:
      url: https://github.com/manga-easy/manga_easy_lint_rules.git
      ref: v1.1.0

flutter:

